export { default as DashboardView } from './DashboardView.vue'
export { default as LoginView } from './LoginView.vue'
export { default as RequestPassword } from './RequestPasswordView.vue'
export { default as ResetPassword } from './ResetPasswordView.vue'
export { default as ProductsView } from './Products/ProductsView.vue'
export { default as UsersView } from './UsersView.vue'
export { default as ReportsView } from './ReportsView.vue'
export { default as NotFoundView } from './NotFoundView.vue'
